# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunterbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysinfo',
            name='Index',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sysinfo',
            name='NPCDelta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sysinfo',
            name='NPCKills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sysinfo',
            name='PlayerKills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sysinfo',
            name='PodKills',
            field=models.IntegerField(null=True),
        ),
    ]
