# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunterbot', '0002_auto_20170602_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='RegionId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sysinfo',
            name='NPCDelta',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sysinfo',
            name='System',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunterbot.System', unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='SystemId',
            field=models.IntegerField(unique=True),
        ),
    ]
